
networks:
  intern-net:
    external: false
  extern-net:
    external: false


services:
  nftlist-common:
    build: ..
    image: nftlist-common
    command: ["echo", "Build-only service"]

  client:
    image: nftlist-common
    container_name: client
    networks:
      - intern-net
    environment:
      - MYROLE=client
    volumes:
      - ./pipes:/run/pipes
      - ../setup/openrc/nftlist:/etc/init.d/nftlist:ro
      - ../setup/openrc/nftlist-refresh.sh:/etc/periodic/daily/nftlist.daily.sh:ro
      - ../nftlist/:/root/nftlist/:ro
      - ../setup/nftlist:/usr/local/bin/nftlist:ro

      - ../lists:/etc/nftlists/included/:ro
      - ../examples:/root/examples:ro

      - ../src/nft_example.py:/root/bin/nft_example.py:ro
      - ../tests:/root/tests:ro

    cap_add: [ 'SYS_ADMIN' ]
    privileged: true

  router:
    image: nftlist-common
    container_name: router
    networks:
      - intern-net
      - extern-net
    environment:
      - MYROLE=router
    volumes:
      - ./pipes:/run/pipes
      - ../setup/openrc/nftlist:/etc/init.d/nftlist:ro
      - ../setup/openrc/nftlist-refresh.sh:/etc/periodic/daily/nftlist.daily.sh:ro
      - ../nftlist/:/root/nftlist/:ro
      - ../setup/nftlist:/usr/local/bin/nftlist:ro

      - ../lists:/etc/nftlists/included/:ro
      - ../examples:/root/examples:ro

      - ../src/nft_example.py:/root/bin/nft_example.py:ro
      - ../tests:/root/tests:ro

    cap_add: [ 'SYS_ADMIN' ]
    privileged: true

  server:
    image: nftlist-common
    container_name: server
    networks:
      - extern-net
    environment:
      - MYROLE=server
    volumes:
      - ./pipes:/run/pipes
      - ../setup/openrc/nftlist:/etc/init.d/nftlist:ro
      - ../setup/openrc/nftlist-refresh.sh:/etc/periodic/daily/nftlist.daily.sh:ro
      - ../nftlist/:/root/nftlist/:ro
      - ../setup/nftlist:/usr/local/bin/nftlist:ro

      - ../lists:/etc/nftlists/included/:ro
      - ../examples:/root/examples:ro

      - ../src/nft_example.py:/root/bin/nft_example.py:ro
      - ../tests:/root/tests:ro

    cap_add: [ 'SYS_ADMIN' ]
    privileged: true

