#!/sbin/openrc-run

extra_started_commands="refresh"

NFTLIST="/usr/bin/python3 -m nftlist"


depend() {
        need nftables
        after networking
}

start() {
        ebegin "Starting ${RC_SVCNAME}"
        $NFTLIST update
        eend $?
}

stop() {
        ebegin "Stopping ${RC_SVCNAME}"
        $NFTLIST purge
        eend $?
}

refresh() {
        $NFTLIST update
}

panic() {
        $NFTLIST panic
}
